[platformio]
default_envs =
  quinled_dig2go
  quinled_diguno
  quinled_diguno_temp
  quinled_diguno_eth
  quinled_diguno_eth_temp
  lilygo_t7_s3_moonhub75
  adafruit_matrix_portal_s3
  esp32-a1s_audio_sender


###############
### GLOBALS ###
###############

[treyturner]
build_flags =
  -D UM_AUDIOREACTIVE_ENABLE
  -D AUTOSAVE_AFTER_SEC=0
  -D WLED_AP_SSID_UNIQUE
  -D WLED_WATCHDOG_TIMEOUT=0
  -D CONFIG_ASYNC_TCP_USE_WDT=0
  -D CONFIG_ASYNC_TCP_STACK_SIZE=9472
  -D WLED_DISABLE_BROWNOUT_DET
  -D ENCODER_CLK_PIN=-1 -D ENCODER_DT_PIN=-1 -D ENCODER_SW_PIN=-1
  -D IRTYPE=0
  !python -c "import os; print(\"-D CLIENT_SSID='\\\"{}\\\"'\".format(os.getenv('IOT_SSID', 'Your_Network')))"
  !python -c "import os; print(\"-D CLIENT_PASS='\\\"{}\\\"'\".format(os.getenv('WPA_KEY', '')))"

build_flags_serial_to_usb =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -D ARDUINO_USB_MSC_ON_BOOT=0
  -D ARDUINO_USB_DFU_ON_BOOT=0

build_flags_hardware_cdc =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MSC_ON_BOOT=0
  -D ARDUINO_USB_DFU_ON_BOOT=1

build_flags_skip_ir =
  -D WLED_DISABLE_INFRARED
  -D IRPIN=-1

build_flags_disable_sync =
  -D WLED_DISABLE_ADALIGHT
  -D WLED_DISABLE_ALEXA
  -D WLED_DISABLE_ESPNOW
  -D WLED_DISABLE_HUESYNC
  -D WLED_DISABLE_LOXONE
  -D WLED_DISABLE_MQTT

build_unflags_common =
  -D WLED_ENABLE_DMX_INPUT
  -D CONFIG_ASYNC_TCP_STACK_SIZE=8192

build_unflags_release_name =
  -D WLED_RELEASE_NAME=\"ESP32\"
  -D WLED_RELEASE_NAME=\"ESP32_Ethernet\"
  -D WLED_RELEASE_NAME=\"ESP32-S3_16MB_opi\"
  -D WLED_RELEASE_NAME=\"ESP32-S3_8MB_qspi\"
  -D WLED_RELEASE_NAME=\"ESP32-S3_Adafruit_Matrixportal\"
  -D WLED_RELEASE_NAME=\"ESP32-S3_16MB_opi_HUB75\"

lib_ignore_common = esp_dmx


[speed_flags]
build_unflags = -Os
build_flags =
  -O2
  -free -fipa-pta
  -fno-jump-tables -fno-tree-switch-conversion
  -freorder-blocks -Wwrite-strings -fstrict-volatile-bitfields


[esp32_stable_v4]
platform = espressif32@ ~6.3.2
platform_packages =
  platformio/framework-arduinoespressif32 @ 3.20009.0
build_flags = -g
  -Wshadow=compatible-local
  -DARDUINO_ARCH_ESP32 -DESP32
  -DCONFIG_LITTLEFS_FOR_IDF_3_2 -DLFS_THREADSAFE
  -D ADC_ATTEN_DB_12=ADC_ATTEN_DB_11
  ${esp32_all_variants.build_flags}
  -D CONFIG_ASYNC_TCP_TASK_STACK_SIZE=9472
  -D WLED_ENABLE_DMX_INPUT
lib_deps =
  ${esp32_all_variants.lib_deps}
  https://github.com/someweisguy/esp_dmx.git#47db25d8c515e76fabcf5fc5ab0b786f98eeade0
  ${env.lib_deps}


[quinboards]
custom_usermods_common =
  audioreactive
  auto_save

build_flags_diguno_common =
  -D WLED_BRAND='"QuinLED"'
  -D ABL_MILLIAMPS_DEFAULT=1250
  -D DATA_PINS=16,3 -D PIXEL_COUNTS=30,30
  -D BTNPIN=0
  -D RLYPIN=-1
  -D AUDIOPIN=36
  -D I2S_CKPIN=-1 -D I2S_WSPIN=-1 -D I2S_SDPIN=-1 -D MCLK_PIN=-1
  -D HW_PIN_SDA=-1 -D HW_PIN_SCL=-1
  -D SR_DMTYPE=254
  -D SR_GAIN=37 -D SR_SQUELCH=10
  ${treyturner.build_flags_skip_ir}

build_flags_temp =
  -D TEMPERATURE_PIN=13
  -D USERMOD_DALLASTEMPERATURE_MEASUREMENT_INTERVAL=10000

build_flags_ethernet =
  -D WLED_USE_ETHERNET
  -D WLED_ETH_DEFAULT=4


#####################
### BOARD CONFIGS ###
#####################

[env:quinled_dig2go]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
custom_usermods = ${quinboards.custom_usermods_common}
build_unflags =
  ${common.build_unflags}
  ${treyturner.build_unflags_common}
  ${treyturner.build_unflags_release_name}
build_flags =
  ${common.build_flags}
  ${esp32_idf_V4.build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  -D WLED_BRAND='"QuinLED"'
  -D WLED_RELEASE_NAME=\"QuinLED_Dig2go\"
  -D SERVERNAME='"QuinLED-Dig2go"'
  -D ABL_MILLIAMPS_DEFAULT=3000
  -D DATA_PINS=16 -D PIXEL_COUNTS=30
  -D BTNPIN=0
  -D IRPIN=5
  -D RLYPIN=12
  -D SR_DMTYPE=1
  -D SR_GAIN=30 -D SR_SQUELCH=10
  -D I2S_CKPIN=18 -D I2S_WSPIN=4 -D I2S_SDPIN=19 -D MCLK_PIN=-1
  -D HW_PIN_SDA=21 -D HW_PIN_SCL=22
lib_deps = ${esp32_idf_V4.lib_deps}
lib_ignore = ${treyturner.lib_ignore_common}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio


[env:quinled_diguno]
board = esp32dev
platform = ${esp32_idf_V4.platform}
platform_packages = ${esp32_idf_V4.platform_packages}
custom_usermods = ${quinboards.custom_usermods_common}
build_unflags =
  ${common.build_unflags}
  ${treyturner.build_unflags_common}
  ${treyturner.build_unflags_release_name}
build_flags =
  ${common.build_flags}
  ${esp32_idf_V4.build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  ${quinboards.build_flags_diguno_common}
  -D WLED_RELEASE_NAME=\"QuinLED_DigUno\"
  -D SERVERNAME='"QuinLED-DigUno"'
lib_deps = ${esp32_idf_V4.lib_deps}
lib_ignore = ${treyturner.lib_ignore_common}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio


[env:quinled_diguno_temp]
extends = env:quinled_diguno
custom_usermods =
  ${quinboards.custom_usermods_common}
  Temperature
build_flags =
  ${env:quinled_diguno.build_flags}
  -D WLED_RELEASE_NAME=\"QuinLED_DigUno_Temp\"
  -D SERVERNAME='"QuinLED-DigUno-Temp"'
  ${quinboards.build_flags_temp}
build_unflags =
  ${env:quinled_diguno.build_unflags}
  -D WLED_RELEASE_NAME=\"QuinLED_DigUno\"
  -D SERVERNAME='"QuinLED-DigUno"'


[env:quinled_diguno_eth]
extends = env:quinled_diguno
build_flags =
  ${env:quinled_diguno.build_flags}
  -D WLED_RELEASE_NAME=\"QuinLED_DigUno_Eth\"
  -D SERVERNAME='"QuinLED-DigUno-Eth"'
  ${quinboards.build_flags_ethernet}
build_unflags =
  ${env:quinled_diguno.build_unflags}
  -D WLED_RELEASE_NAME=\"QuinLED_DigUno\"
  -D SERVERNAME='"QuinLED-DigUno"'


[env:quinled_diguno_eth_temp]
extends = env:quinled_diguno
custom_usermods =
  ${quinboards.custom_usermods_common}
  Temperature
build_flags =
  ${env:quinled_diguno.build_flags}
  -D WLED_RELEASE_NAME=\"QuinLED_DigUno_Eth_Temp\"
  -D SERVERNAME='"QuinLED-DigUno-Eth-Temp"'
  ${quinboards.build_flags_temp}
  ${quinboards.build_flags_ethernet}
build_unflags =
  ${env:quinled_diguno.build_unflags}
  -D WLED_RELEASE_NAME=\"QuinLED_DigUno\"
  -D SERVERNAME='"QuinLED-DigUno"'


[env:lilygo_t7_s3_moonhub75]
platform = ${esp32s3.platform}
platform_packages = ${esp32s3.platform_packages}
board = lilygo-t7-s3
board_build.arduino.memory_type = qio_opi
custom_usermods =
  audioreactive
  auto_save
  Battery
  animartrix
build_unflags =
  ${common.build_unflags}
  ${treyturner.build_unflags_common}
  ${treyturner.build_unflags_release_name}
build_flags =
  ${common.build_flags}
  ${esp32s3.build_flags}
  ${hub75.build_flags}
  ${hub75.s3_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_hardware_cdc}
  ${treyturner.build_flags_disable_sync}
  -D WLED_BRAND='"Lilygo"'
  -D WLED_RELEASE_NAME=\"Lilygo_T7_S3_MOONHUB75\"
  -D SERVERNAME='"Lilygo-T7-S3-MOONHUB75"'
  -D MOONHUB_S3_PINOUT
  -D LEDPIN=14 -D DATA_PINS=14
  -D RLYPIN=-1 -D AUDIOPIN=-1
  -D I2S_SDPIN=10 -D I2S_CKPIN=11 -D I2S_WSPIN=12 -D MCLK_PIN=-1
  -D USERMOD_BATTERY_MEASUREMENT_PIN=2
  -D STATUSLED=17
  -D BTNPIN=0
  ${treyturner.build_flags_skip_ir}
  -D SR_DMTYPE=254
  -D SR_GAIN=37 -D SR_SQUELCH=10
  -D ABL_MILLIAMPS_DEFAULT=1250
  -D WLED_MAX_MATRIX_DIMENSION=256
  -D WLED_ENABLE_PIXART
lib_deps =
  ${esp32s3.lib_deps}
  ${hub75.lib_deps}
lib_ignore = ${treyturner.lib_ignore_common}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.extreme_partitions}
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.f_flash = 80000000L
board_build.flash_mode = qio


[env:adafruit_matrix_portal_s3]
platform = ${esp32s3.platform}
platform_packages = ${esp32s3.platform_packages}
board = adafruit_matrixportal_esp32s3_wled
board_build.arduino.memory_type = qio_qspi
custom_usermods =
  audioreactive
  auto_save
  animartrix
build_unflags =
  ${common.build_unflags}
  ${treyturner.build_unflags_common}
  ${treyturner.build_unflags_release_name}
build_flags =
  ${common.build_flags}
  ${esp32s3.build_flags}
  ${hub75.build_flags}
  ${hub75.s3_build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_hardware_cdc}
  ${treyturner.build_flags_disable_sync}
  -D WLED_BRAND='"Adafruit"'
  -D WLED_RELEASE_NAME=\"Adafruit_Matrix_Portal_S3\"
  -D SERVERNAME='"Adafruit-Matrix-Portal-S3"'
  -D ARDUINO_ADAFRUIT_MATRIXPORTAL_ESP32S3
  -D LEDPIN=14 -D DATA_PINS=14
  -D RLYPIN=-1 -D AUDIOPIN=-1
  -D I2S_SDPIN=-1 -D I2S_CKPIN=-1 -D I2S_WSPIN=-1 -D MCLK_PIN=-1
  -D BTNPIN=7
  -D STATUSLED=17
  ${treyturner.build_flags_skip_ir}
  -D SR_DMTYPE=254
  -D SR_GAIN=37 -D SR_SQUELCH=10
  -D ABL_MILLIAMPS_DEFAULT=1250
  -D WLED_MAX_MATRIX_DIMENSION=256
  -D WLED_ENABLE_PIXART
lib_deps =
  ${esp32s3.lib_deps}
  ${hub75.lib_deps}
lib_ignore = ${treyturner.lib_ignore_common}
monitor_filters = esp32_exception_decoder
board_build.partitions = tools/partitions-8MB_spiffs-tinyuf2.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.f_flash = 80000000L
board_build.flash_mode = qio


[env:esp32-a1s_audio_sender]
board = esp32dev
platform = ${esp32_stable_v4.platform}
platform_packages = ${esp32_stable_v4.platform_packages}
custom_usermods = audioreactive
build_unflags =
  ${common.build_unflags}
  ${treyturner.build_unflags_common}
  ${treyturner.build_unflags_release_name}
build_flags =
  ${common.build_flags}
  ${esp32_stable_v4.build_flags}
  ${treyturner.build_flags}
  ${treyturner.build_flags_serial_to_usb}
  ${treyturner.build_flags_disable_sync}
  ${treyturner.build_flags_skip_ir}
  -D WLED_BRAND='"Ai-Thinker"'
  -D WLED_RELEASE_NAME=\"Ai-Thinker_ESP32-A1S_Audio_Sender\"
  -D SERVERNAME='"ESP32-A1S-Audio-Sender"'
  -D DATA_PINS=16 -D PIXEL_COUNTS=1
  -D ABL_MILLIAMPS_DEFAULT=250
  -D BTNPIN=36 -D AUDIOPIN=-1 -D RLYPIN=-1
  -D I2S_SDPIN=35 -D I2S_WSPIN=25 -D I2S_CKPIN=27 -D MCLK_PIN=0
  -D I2CSDAPIN=33 -D I2CSCLPIN=32
  -D SR_DMTYPE=6 -D SR_GAIN=37 -D SR_SQUELCH=10
  -D WLED_DISABLE_2D
  -D WLED_DISABLE_PIXELFORGE
  -D WLED_DISABLE_PARTICLESYSTEM1D
  -D WLED_MAX_BUTTONS=1
lib_deps = ${esp32_stable_v4.lib_deps}
lib_ignore =
  ${treyturner.lib_ignore_common}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
board_build.flash_mode = dio
